### ISSUE TITLE
newbie question

### ISSUE THREAD

**Issue by tlcrame** [ontio/Anniversary#10]
why pattern `\\` matches `\`? 

- Is pattern not raw string here, or can have escape characters?The documentation do not mention anything about it.
- If so, we need to preprocess escape characters before regex match?
- Then how many escape characters we need to handle? 
- Is `\+` escapes to char `+` or repeat `\` more one times?

**Comment by Honglei-Cong** [comment]
<code>\\\\</code> as a pattern, the first <code>\\</code> is escape char.
Escape char is common in Posix BRE, please take that as reference.  But in our final testset, all patterns are valid patterns.  So, you can process escape chars in some simple way.

**Comment by tlcrame** [comment]
@Honglei-Cong , thanks for reply. one more question: I currently assume `^` will just appear in the first place or after `[` char or escaped with `\`, and `$` appear at the last place or escaped with `\`.    so `^a\^a[^b\^]` and `\$aa$` is valid, but pattern `^abc^d` and `a$b$` is not. Is it reasonable? 
Since no failed test cases are allowed, it waste me a lot of time interpreting the question itself. I just want to make sure the assumption is ok to let us go ahead to do the actual coding.

**Comment by Honglei-Cong** [comment]
@tlcrame 
Yes, it's right.
